name: Daily Pizza Update
on:
  schedule:
    - cron: '0 8 * * *'  # Каждый день в 8:00 утра
  workflow_dispatch:  # Можно запустить вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run Scraper
        run: |
          curl -X GET "https://pizza-syktyvkar.vercel.app/api/scrape"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          YANDEX_API_KEY: ${{ secrets.YANDEX_API_KEY }}